import sys

src = open('MATLAB_rsf.py', encoding='utf-8').read()
m_start = src.find('\n    def _update_autotune_vimp_chart(self):')
m_next_def = src.find('\n    def ', m_start + 40)

if m_start == -1 or m_next_def == -1:
    print('BOUNDS NOT FOUND'); sys.exit(1)

new_method = (
    "\n"
    "    def _update_autotune_vimp_chart(self):\n"
    "        \"\"\"Screening scatter: un punto por semilla, ejes X e Y seleccionables.\n"
    "        Si ambos ejes son metricas C-index dibuja la referencia y=x.\"\"\"\n"
    "        import numpy as _np_v\n"
    "        fig = getattr(self, '_autotune_vimp_fig', None)\n"
    "        canvas = getattr(self, '_autotune_vimp_canvas', None)\n"
    "        seed_recs = list(getattr(self, '_autotune_current_seed_metrics', None) or [])\n"
    "        cand_n = getattr(self, '_autotune_current_candidate_n', 0)\n"
    "        info_var = getattr(self, '_autotune_vimp_info_var', None)\n"
    "        if fig is None or canvas is None:\n"
    "            return\n"
    "\n"
    "        _metric_key_map = {'OOB': 'oob', 'C-CV': 'cv', 'C-Test': 'ctest', 'BSS': 'bss'}\n"
    "        _metric_label_map = {'oob': 'OOB', 'cv': 'C-CV', 'ctest': 'C-Test', 'bss': 'BSS'}\n"
    "        _c_index_metrics = {'oob', 'cv', 'ctest'}\n"
    "\n"
    "        x_var = getattr(self, '_autotune_screen_x_var', None)\n"
    "        y_var = getattr(self, '_autotune_screen_y_var', None)\n"
    "        x_label = x_var.get() if x_var is not None else 'OOB'\n"
    "        y_label = y_var.get() if y_var is not None else 'C-Test'\n"
    "        x_key = _metric_key_map.get(x_label, 'oob')\n"
    "        y_key = _metric_key_map.get(y_label, 'ctest')\n"
    "\n"
    "        fig.clear()\n"
    "\n"
    "        if not seed_recs:\n"
    "            ax0 = fig.add_subplot(111)\n"
    "            ax0.text(0.5, 0.5, 'Esperando semillas...', ha='center', va='center',\n"
    "                     fontsize=9, color='#9ca3af')\n"
    "            ax0.set_axis_off()\n"
    "            canvas.draw_idle()\n"
    "            if info_var is not None:\n"
    "                try:\n"
    "                    info_var.set('Esperando modelos...')\n"
    "                except Exception:\n"
    "                    pass\n"
    "            return\n"
    "\n"
    "        ax = fig.add_subplot(111)\n"
    "        n_s = len(seed_recs)\n"
    "\n"
    "        xs, ys, labels = [], [], []\n"
    "        for i, r in enumerate(seed_recs):\n"
    "            xv = r.get(x_key)\n"
    "            yv = r.get(y_key)\n"
    "            if xv is not None and yv is not None:\n"
    "                try:\n"
    "                    xs.append(float(xv))\n"
    "                    ys.append(float(yv))\n"
    "                    labels.append(f'S{i+1}')\n"
    "                except (TypeError, ValueError):\n"
    "                    pass\n"
    "\n"
    "        if not xs:\n"
    "            ax.text(0.5, 0.5, 'Sin datos para los ejes seleccionados',\n"
    "                    ha='center', va='center', fontsize=8, color='#9ca3af')\n"
    "            ax.set_axis_off()\n"
    "        else:\n"
    "            _seed_colors = ['#2563eb', '#16a34a', '#dc2626', '#9333ea',\n"
    "                            '#f59e0b', '#0891b2', '#be185d', '#65a30d']\n"
    "            for i, (xv, yv, lbl) in enumerate(zip(xs, ys, labels)):\n"
    "                col = _seed_colors[i % len(_seed_colors)]\n"
    "                ax.scatter([xv], [yv], color=col, s=62, zorder=4, alpha=0.88)\n"
    "                ax.annotate(lbl, (xv, yv), textcoords='offset points',\n"
    "                            xytext=(5, 4), fontsize=7, color=col, fontweight='bold')\n"
    "                ax.annotate(f'{xv:.3f},{yv:.3f}', (xv, yv), textcoords='offset points',\n"
    "                            xytext=(5, -8), fontsize=6, color='#4b5563')\n"
    "            # Connect points with thin line\n"
    "            if len(xs) > 1:\n"
    "                ax.plot(xs, ys, color='#d1d5db', linewidth=0.8, zorder=2, alpha=0.6)\n"
    "            # y=x reference when both axes are C-index type\n"
    "            if x_key in _c_index_metrics and y_key in _c_index_metrics:\n"
    "                _all = list(xs) + list(ys)\n"
    "                _lo = max(0.0, min(_all) - 0.05)\n"
    "                _hi = min(1.0, max(_all) + 0.05)\n"
    "                ax.plot([_lo, _hi], [_lo, _hi], color='#94a3b8', linewidth=1.1,\n"
    "                        linestyle='--', alpha=0.7, label='y = x', zorder=1)\n"
    "                ax.legend(fontsize=6, loc='lower right', framealpha=0.55)\n"
    "            ax.set_xlabel(_metric_label_map.get(x_key, x_label), fontsize=7)\n"
    "            ax.set_ylabel(_metric_label_map.get(y_key, y_label), fontsize=7)\n"
    "            ax.set_title(f'Candidato #{cand_n} \u2014 {n_s} semilla(s)', fontsize=8, pad=3)\n"
    "            ax.tick_params(labelsize=6)\n"
    "            ax.grid(True, linewidth=0.4, alpha=0.35)\n"
    "\n"
    "        fig.tight_layout(pad=0.7)\n"
    "        canvas.draw_idle()\n"
    "\n"
    "        if info_var is not None:\n"
    "            try:\n"
    "                info_var.set(f'Candidato #{cand_n} | {n_s} semilla(s) | X={x_label} Y={y_label}')\n"
    "            except Exception:\n"
    "                pass\n"
    "\n"
)

new_src = src[:m_start] + new_method + src[m_next_def:]
open('MATLAB_rsf.py', 'w', encoding='utf-8').write(new_src)
print('DONE, new method lines:', new_method.count('\n'))
